// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTlGTgskb_xyftgUaBJh6s0vgx6n31ihc',
    appId: '1:188432300219:web:1a1ed754ce69e0313cd19e',
    messagingSenderId: '188432300219',
    projectId: 'prioritize-it-6c0ed',
    authDomain: 'prioritize-it-6c0ed.firebaseapp.com',
    storageBucket: 'prioritize-it-6c0ed.firebasestorage.app',
    measurementId: 'G-VY83XTKD3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe50GDUswLbNclLfSkD1c051CLdGFw_Oo',
    appId: '1:188432300219:android:b6a12272cfbb23183cd19e',
    messagingSenderId: '188432300219',
    projectId: 'prioritize-it-6c0ed',
    storageBucket: 'prioritize-it-6c0ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnsfX1cT6hNS8GSEBR1uK0pU5cmLzrRpI',
    appId: '1:188432300219:ios:2439e8a370b9e4d73cd19e',
    messagingSenderId: '188432300219',
    projectId: 'prioritize-it-6c0ed',
    storageBucket: 'prioritize-it-6c0ed.firebasestorage.app',
    iosBundleId: 'com.example.prioritizeIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnsfX1cT6hNS8GSEBR1uK0pU5cmLzrRpI',
    appId: '1:188432300219:ios:2439e8a370b9e4d73cd19e',
    messagingSenderId: '188432300219',
    projectId: 'prioritize-it-6c0ed',
    storageBucket: 'prioritize-it-6c0ed.firebasestorage.app',
    iosBundleId: 'com.example.prioritizeIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTlGTgskb_xyftgUaBJh6s0vgx6n31ihc',
    appId: '1:188432300219:web:0e9cb061b18b431b3cd19e',
    messagingSenderId: '188432300219',
    projectId: 'prioritize-it-6c0ed',
    authDomain: 'prioritize-it-6c0ed.firebaseapp.com',
    storageBucket: 'prioritize-it-6c0ed.firebasestorage.app',
    measurementId: 'G-V4MQKCM461',
  );
}
